export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const CREATE_POLL_REQUEST = "CREATE_POLL_REQUEST";
export const CREATE_POLL_ERROR = "CREATE_POLL_ERROR";
export const CREATE_POLL_SUCCESS = "CREATE_POLL_SUCCESS";

export const SHOW_POLL_REQUEST = "SHOW_POLL_REQUEST";
export const SHOW_POLL_ERROR = "SHOW_POLL_ERROR";
export const SHOW_POLL_SUCCESS = "SHOW_POLL_SUCCESS";
