export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const CREATE_POLL_REQUEST = "CREATE_POLL_REQUEST";
export const CREATE_POLL_ERROR = "CREATE_POLL_ERROR";
export const CREATE_POLL_SUCCESS = "CREATE_POLL_SUCCESS";

export const SHOW_POLL_REQUEST = "SHOW_POLL_REQUEST";
export const SHOW_POLL_ERROR = "SHOW_POLL_ERROR";
export const SHOW_POLL_SUCCESS = "SHOW_POLL_SUCCESS";

export const REQ_POLL_BY_ID = "REQ_POLL_BY_ID";
export const GET_POLL_BY_ID = "GET_POLL_BY_ID";

export const DELETE_POLL_REQ = "DELETE_POLL_REQ";
export const DELETE_POLL_ERROR = "DELETE_POLL_ERROR";
export const DELETE_POLL_SUCCESS = "DELETE_POLL_SUCCESS";

export const ADD_OPTION_REQ = "ADD_OPTION_REQ";
export const ADD_OPTION_SUCCESS = "ADD_OPTION_SUCCESS";

export const DELETE_OPTION_REQ = "DELETE_OPTION_REQ";
export const DELETE_OPTION_SUCCESS = "DELETE_OPTION_SUCCESS";

export const EDIT_TITLE_REQ = "EDIT_TITLE_REQ";
export const EDIT_TITLE_SUCCESS = "EDIT_TITLE_SUCCESS";

export const ADD_VOTE_REQ = "ADD_VOTE_REQ";
export const ADD_VOTE_SUCCESS = "ADD_VOTE_SUCCESS";
